#!/usr/bin/env python

# Based on the sxfm script from Darren Dale's praxes

from __future__ import absolute_import

import sys

from PyQt4 import QtGui

from titan.frontend import mainwindow

if __name__ == "__main__":
    qapp = QtGui.QApplication(sys.argv)
    
    aw = mainwindow.AppWindow()
    aw.setWindowTitle("TITAN")
    aw.show()
    
    sys.exit(qapp.exec_())